# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mp4togif.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Program(object):
    def setupUi(self, Program):
        Program.setObjectName("Program")
        Program.setFixedSize(571, 199)
        self.centralwidget = QtWidgets.QWidget(Program)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(10, 10, 201, 31))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("mp4.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.filePath = QtWidgets.QLineEdit(self.centralwidget)
        self.filePath.setGeometry(QtCore.QRect(160, 50, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.filePath.setFont(font)
        self.filePath.setStyleSheet("")
        self.filePath.setText("")
        self.filePath.setObjectName("filePath")
        self.mp4_label = QtWidgets.QLabel(self.centralwidget)
        self.mp4_label.setGeometry(QtCore.QRect(10, 50, 161, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.mp4_label.setFont(font)
        self.mp4_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mp4_label.setObjectName("mp4_label")
        self.gif_label = QtWidgets.QLabel(self.centralwidget)
        self.gif_label.setGeometry(QtCore.QRect(10, 90, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.gif_label.setFont(font)
        self.gif_label.setAlignment(QtCore.Qt.AlignCenter)
        self.gif_label.setObjectName("gif_label")
        self.savePath = QtWidgets.QLineEdit(self.centralwidget)
        self.savePath.setGeometry(QtCore.QRect(160, 90, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.savePath.setFont(font)
        self.savePath.setStyleSheet("")
        self.savePath.setText("")
        self.savePath.setObjectName("savePath")
        self.browse = QtWidgets.QPushButton(self.centralwidget)
        self.browse.setGeometry(QtCore.QRect(450, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.browse.setFont(font)
        self.browse.setStyleSheet("QPushButton {\n"
"    border-style: outset;\n"
"    border: 1px solid gray;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(203, 203, 203);\n"
"}\n"
"")
        self.browse.setObjectName("browse")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(450, 90, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.save.setFont(font)
        self.save.setStyleSheet("QPushButton {\n"
"    border-style: outset;\n"
"    border: 1px solid gray;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(203, 203, 203);\n"
"}\n"
"")
        self.save.setObjectName("save")
        self.convert = QtWidgets.QPushButton(self.centralwidget)
        self.convert.setGeometry(QtCore.QRect(370, 150, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.convert.setFont(font)
        self.convert.setStyleSheet("QPushButton {\n"
"    border-style: outset;\n"
"    border: 1px solid gray;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(227, 227, 227);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(203, 203, 203);\n"
"}\n"
"")
        self.convert.setObjectName("convert")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(230, 10, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.frame_slider = QtWidgets.QSlider(self.centralwidget)
        self.frame_slider.setGeometry(QtCore.QRect(160, 140, 151, 21))
        self.frame_slider.setOrientation(QtCore.Qt.Horizontal)
        self.frame_slider.setObjectName("frame_slider")
        self.fd_label = QtWidgets.QLabel(self.centralwidget)
        self.fd_label.setGeometry(QtCore.QRect(10, 130, 141, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.fd_label.setFont(font)
        self.fd_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fd_label.setObjectName("fd_label")
        self.cmp_label = QtWidgets.QLabel(self.centralwidget)
        self.cmp_label.setGeometry(QtCore.QRect(20, 160, 131, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.cmp_label.setFont(font)
        self.cmp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cmp_label.setObjectName("cmp_label")
        self.compr_label = QtWidgets.QSlider(self.centralwidget)
        self.compr_label.setGeometry(QtCore.QRect(160, 170, 151, 21))
        self.compr_label.setOrientation(QtCore.Qt.Horizontal)
        self.compr_label.setObjectName("compr_label")
        self.localization = QtWidgets.QPushButton(self.centralwidget)
        self.localization.setGeometry(QtCore.QRect(530, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.localization.setFont(font)
        self.localization.setStyleSheet("QPushButton {\n"
"    border-style: outset;\n"
"    border: 1px solid gray;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(227, 227, 227);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(203, 203, 203);\n"
"}\n"
"")
        self.localization.setObjectName("localization")
        self.frame_count = QtWidgets.QLabel(self.centralwidget)
        self.frame_count.setGeometry(QtCore.QRect(310, 140, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frame_count.setFont(font)
        self.frame_count.setStyleSheet("QLabel {\n"
"    border-style: none;\n"
"}\n"
"")
        self.frame_count.setAlignment(QtCore.Qt.AlignCenter)
        self.frame_count.setObjectName("frame_count")
        self.cmp_count = QtWidgets.QLabel(self.centralwidget)
        self.cmp_count.setGeometry(QtCore.QRect(310, 170, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cmp_count.setFont(font)
        self.cmp_count.setStyleSheet("QLabel {\n"
"    border-style: none;\n"
"\n"
"}\n"
"")
        self.cmp_count.setAlignment(QtCore.Qt.AlignCenter)
        self.cmp_count.setObjectName("cmp_count")
        Program.setCentralWidget(self.centralwidget)

        self.retranslateUi(Program)
        QtCore.QMetaObject.connectSlotsByName(Program)

    def retranslateUi(self, Program):
        _translate = QtCore.QCoreApplication.translate
        Program.setWindowTitle(_translate("Program", "MainWindow"))
        self.mp4_label.setText(_translate("Program", "MP4 File"))
        self.gif_label.setText(_translate("Program", "GIF location"))
        self.browse.setText(_translate("Program", "Browse"))
        self.save.setText(_translate("Program", " Save to"))
        self.convert.setText(_translate("Program", "Convert video to GIF"))
        self.statusLabel.setText(_translate("Program", "Ready to work!"))
        self.fd_label.setText(_translate("Program", "Frame duration"))
        self.cmp_label.setText(_translate("Program", "Compression"))
        self.localization.setText(_translate("Program", "EN"))
        self.frame_count.setText(_translate("Program", "0"))
        self.cmp_count.setText(_translate("Program", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Program = QtWidgets.QMainWindow()
    ui = Ui_Program()
    ui.setupUi(Program)
    Program.show()
    sys.exit(app.exec_())
